version: '3.3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - pimcorenet
    php:
        build: ./docker/php
        volumes:
            - .:/var/www/html
        networks:
          - pimcorenet

networks:
    pimcorenet: